apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}-agent
spec:
  type: {{ .Values.jnlp.service.type }}
  ports:
    - port: {{ .Values.jnlp.service.externalPort }}
      targetPort: {{ .Values.jnlp.service.internalPort }}
  selector:
    app: {{ .Values.appname }}
    release: {{ .Release.Name }}
