apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
type: Opaque
data:
  jenkins-admin-user: {{ .Values.master.adminUser | b64enc | quote }}
  jenkins-admin-password: {{ .Values.master.adminPassword | b64enc | quote }}
  
