apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  labels:
    app: jenkins-k8s
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appname }} 
